const global = {
  CastCrew: [
    { label: "Cast", value: "cast" },
    { label: "Crew", value: "crew" },
  ],

  genre: [
    { label: "Action", value: "Action" },
    { label: "Adventure", value: "Adventure" },
    { label: "Animation", value: "Animation" },
    { label: "Biography", value: "Biography" },
    { label: "Comedy", value: "Comedy" },
    { label: "Crime", value: "Crime" },
    { label: "Documentary", value: "Documentary" },
    { label: "Drama", value: "Drama" },
    { label: "Family", value: "Family" },
    { label: "Fantasy", value: "Fantasy" },
    { label: "History", value: "History" },
    { label: "Horror", value: "Horror" },
    { label: "Music", value: "Music" },
    { label: "Musical", value: "Musical" },
    { label: "Mystery", value: "Mystery" },
    { label: "Romance", value: "Romance" },
    { label: "Science Fiction", value: "Science Fiction" },
    { label: "Sports", value: "Sports" },
    { label: "Superhero", value: "Superhero" },
    { label: "Thriller", value: "Thriller" },
    { label: "TV Movie", value: "TV Movie" },
    { label: "War", value: "War" },
    { label: "Western", value: "Western" },
    { label: "Disaster", value: "Disaster" },
    { label: "Spy", value: "Spy" },
    { label: "Martial Arts", value: "Martial Arts" },
    { label: "Coming of Age", value: "Coming of Age" },
    { label: "Psychological Thriller", value: "Psychological Thriller" },
    { label: "Slasher", value: "Slasher" },
    { label: "Zombie", value: "Zombie" },
    { label: "Vampire", value: "Vampire" },
    { label: "Paranormal", value: "Paranormal" },
    { label: "Time Travel", value: "Time Travel" },
    { label: "Cyberpunk", value: "Cyberpunk" },
    { label: "Dystopian", value: "Dystopian" },
    { label: "Mockumentary", value: "Mockumentary" },
    { label: "Stand-Up Comedy", value: "Stand-Up Comedy" },
    { label: "Political Drama", value: "Political Drama" },
    { label: "Legal Drama", value: "Legal Drama" }
  ],
  certificate: [
    { value: 'U', label: 'U - Universal' },
    { value: 'U+', label: 'U+ - Universal with Caution' },
    { value: 'UA', label: 'UA - Parental Guidance (under 12)' },
    { value: 'A', label: 'A - Adults Only (18+)' },
    { value: 'S', label: 'S - Special Audience (Doctors, Scientists, etc.)' },
  ]
}

export default global;